### PR TITLE
utils: Introduce FileUtils class

### PR DESCRIPTION
**Pull request by mhmdeve**
Change-Id: Icbfa068fa0db2ae28436063072dd4b576f1b2be1

FileUtils: Add util to check if a file exists

Change-Id: I565744821346c90ff670704a13fffc7bf464ff71
Signed-off-by: gtpitch <bmontagu@gmail.com>
Signed-off-by: Josh Fox(XlxFoXxlX) <joshfox87@gmail.com>
Signed-off-by: Anirudh Gupta <anirudhgupta109@gmail.com>
Signed-off-by: Josh Fox (XlxFoXxlX) <joshfox87@gmail.com>
Signed-off-by: jhonboy121 <alfredmathew05@gmail.com>

### CODE REVIEW

**Comment by npv12** [comment]
You clearly picked it from somewhere but authorship? What's that?
On a more serious note give proper authorship to "MikeNG <mailto:mikeioannina@gmail.com>"

**Comment by npv12** [comment]
You clearly picked it from somewhere but authorship? What's that?
On a serious note, give it to MikeNG mikeioannina@gmail.com

**Comment by joeyhuab** [comment]
I'll pick it myself with proper authorship.

**Comment by mhmdeve** [comment]
> You clearly picked it from somewhere but authorship? What's that? On a serious note, give it to MikeNG [mikeioannina@gmail.com](mailto:mikeioannina@gmail.com)

I apologise. That was a mistake by me.

**Comment by mhmdeve** [comment]
> I'll pick it myself with proper authorship.

Kindly Pick this also: https://github.com/AOSP-Krypton/frameworks_base/commit/35e94d9da6592ae2d4077e1132be1d948f0e526e

**Pull request closed without merging**
